language: go

sudo: required

go:
  - master

install:
  - go get -u golang.org/x/vgo

# Travis assumes `scripts: make`

notifications:
  email: false

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
